### ISSUE TITLE
>>source format variable is missing

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol4gnucobol#13]
... found the change in e60a717ca05c60727506703bffc74f4e863525d5, but don't understand it as it is supported in GnuCOBOL since 2.x (implemented September 2016, to be more specific).

Similar other features originally coming from Micro Focus (or from other COBOL dialects, taken into Micro Focus COBOL later), most of those are not GA, so that's fine. One thing that seems to be gone but is supported since years: `$SET` (obviously not fully supported, but the amount of support is increasing).

**Comment by spgennard** [comment]
The documentation says;

> 2.1.3 Source format
> GnuCOBOL supports both fixed and free source format. The default format is the fixed format. This can be overridden either by the >>SOURCE [FORMAT] [IS] {FIXED|FREE} directive, or by one of the following options:
> 
> -free, -F
> Free format. The program-text area starts in column 1 and continues till the end of line (effectively 255 characters in GnuCOBOL).
> 
> -fixed
> Fixed format. Source code is divided into: columns 1-6, the sequence number area; column 7, the indicator area; columns 8-72, the program-text area; and columns 72-80 as the reference area.[3](https://gnucobol.sourceforge.io/doc/gnucobol.html#FOOT3)

https://gnucobol.sourceforge.io/doc/gnucobol.html#Source-format

**Comment by spgennard** [comment]
Closed until the GnuCOBOL compiler supports, tests it and documents it.

**Comment by spgennard** [comment]
fyi - The code has been changed and has been included but is currently disabled until it becomes a supported feature, please re-open when that day arrives

**Comment by GitMensch** [comment]
Thank you. The GnuCOBOL internal testsuite actually runs the test since its implementation; but you are definitely right that the documentation about this $SET / >> directive is lacking. I'll drop a ping when this is fixed, possibly takes a while.

**Comment by spgennard** [comment]
The cli also is lacking support for it as well.

**Comment by GitMensch** [comment]
If I remember correctly: `-fixed -ftext-col=250` would be the cli pendant of MF's `-C SOURCEFORMAT"VARIABLE"`.
