### ISSUE TITLE
Incorrect indenting for a new line after a DISPLAY with litteral

### ISSUE THREAD

**Issue by ccoq** [spgennard/vscode_cobol4gnucobol#14]
Hello,

I have found a problem with indentation while adding new lines in programs without dots in paragraph.

I made this program to test : 
`
       IDENTIFICATION DIVISION.
           PROGRAM-ID. PGMTEST.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 CPT PIC 9(9).
        
       PROCEDURE DIVISION.
           DISPLAY 'HELLO'
           PERFORM VARYING CPT FROM 1 BY 1 UNTIL CPT > 50
              DISPLAY 'IN LOOP'  
           END-PERFORM
           DISPLAY 'GOODBYE'
           GOBACK
       .
`

If I add a new line after the DISPLAY 'GOODBYE' instruction, the new line is indenting (which is not expected).
I made a test : if I add a dot after the DISPLAY 'GOODBYE', the new line doesn't indent, but it's not our way of coding.

If I add a new line after the END-PERFORM, the new line doesn't indent. 
So it doesn't seems to be a problem linked to the dot.

Thanks for your work.
Best regards

**Comment by GitMensch** [comment]
The extension does something reasonable: indent for more things you want to `DISPLAY` (or more clauses to add) - both is not available for `END-PERFORM`.

What happens if your press [Backspace] or [Shift]+[Tab] in the indented line? Wouldn't this be reasonable or would you personally feel the need for a setting to adjust where the indent is done (if there is / could be; mainly asking here, not suggesting it should).

**Comment by ccoq** [comment]
Thanks for the quick answer.
I tried another case : if do DISPLAY CPT (display a variable), and I add a new line, there is no indentation. Indentation seems to be added if the DISPLAY finishes by a litteral (DISPLAY 'GOODBYE' for example).

If I press backspace, it removes 3 spaces and I go from column 16 to 13, which is not convenient (margin B starts at column 12).
A setting may be to complicated to implement. I suggest to disable auto-indent for new lines. Only keep the current column. For example, if the user starts his line at column 16 and he starts a new line, the new line will begin at column 16 too.

**Comment by spgennard** [comment]
@ccoq I am not sure what @GitMensch, is talking about but as the author of the extension, I have made a tweak, as I think recent vscode changes for bracket handling are causing the issue.

**Comment by ccoq** [comment]
Thanks. I just refreshed the plugins, it works well now !

**Comment by spgennard** [comment]
Glad to hear that worked
