### ISSUE TITLE
Getting result after the task of compilation or check syntax

### ISSUE THREAD

**Issue by ccoq** [spgennard/vscode_cobol4gnucobol#15]
Is it possible to return the state of compilation (successful / not successful) after task is done ?
I would like to get it to know if a problem occured.

In my case, I execute the compilation task with the vscode.commands.executeCommand(...) instruction, and this instruction has the ability to return if the command is successful.

Thanks in advance.

**Comment by spgennard** [comment]
Not sure this has anything to do with this extension, it sounds like a generic vscode question.

**Comment by ccoq** [comment]
You're right. 
Apparently in vscode, commands can return status, but tasks don't.
This issue is not one and can be closed.

Thanks for your answer.
