### ISSUE TITLE
FR: provide features also for new files

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol4gnucobol#16]
To reproduce:
* create an empty file
* add program source

Result:
* the layout is empty
* go to definition doesn't work

Once the file is saved, both works.
I _guess_ this is about using the "editor" content instead of the "file" content.

**Comment by spgennard** [comment]
This is expected behaviour for this extension.

**Comment by GitMensch** [comment]
Is it possible to make the behaviour identical between bitlang.cobol and bitlang.gnucobol (in whatever direction)?

**Comment by spgennard** [comment]
Given a more advanced GnuCOBOL centric extension is being put together this
seems a short issue, do you not agree?

If so, Upon it's arrival, enabling the transition to it seems better
approach.
