### ISSUE TITLE
Why isn't bitlang.cobol available for VSCodium ? 

### ISSUE THREAD

**Issue by AnthraxBass** [spgennard/vscode_cobol4gnucobol#19]
It's missing in the extensions list.

**Comment by spgennard** [comment]
You use this to install it from the visual studio market place

https://open-vsx.org/extension/zokugun/vsix-manager

Please nite this issue page is for GnuCOBOL not the COBOL extension.

**Comment by AnthraxBass** [comment]
Thank you!
