### ISSUE TITLE
syntax highlight issue for `CHAINING`

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol4gnucobol#4]
```cobol
01  newline pic x value x'0A'.
01  tab pic x value x'09'.

procedure division chaining  city-file-name country-file-name.
start-worldcities1.
    display newline 'starting worldcities1' newline end-display

    if city-file-name = 'techtonics'
        call 'techtonics' using command-file-name techtonics end-call
        stop run
    end-if
```

highlights the `chain` but not the `ing`. Main issue: highlighting should not stop in the middle of the word. Secondary issue: `chaining` is not colored:

![grafik](https://user-images.githubusercontent.com/6699539/133853742-0437c439-d5ee-4b09-8211-a9021a9fa6f9.png)

It also highlights two variables in red - what was the reason for that (You've told me years ago, but I can't remember)?

**Comment by spgennard** [comment]
fixed

**Comment by GitMensch** [comment]
Confirmed, thanks.
