### ISSUE TITLE
FR: adjust to make available as web extension

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol4gnucobol#9]
as is the case for the "parent" extension vscode_cobol

**Comment by GitMensch** [comment]
Hey bot, please give @spgennard a bit more time to answer.

**Comment by GitMensch** [comment]
Maybe stale config should be extended here because _reasonably_ the current work of @spgennard goes to bitlang.cobol.

**Comment by GitMensch** [comment]
@spgennard Can you specify what actually is necessary to do for this extension to work as web extension? "Only" a different entry point?

**Comment by spgennard** [comment]
@GitMensch - That is just the start of the process, you need to ensure the code does not access any files etc.

**Comment by GitMensch** [comment]
Thank you for the information, I'm looking forward to see that adjustments in an upcoming release!

**Comment by GitMensch** [comment]
Friendly ping - current version of bitlang.cobol can be used on vscode.dev, bitlang.gnucobol cannot be installed, has a remark "not available for web".
